### ISSUE TITLE
练习9.3的并发安全问题

### ISSUE THREAD

**Issue by shangxiaomi** [linehk/gopl#11]
[练习9.3的并发安全问题](https://github.com/linehk/gopl/blob/master/ch9/exercise9.3/memo.go)

会不会发生并发安全问题
t1,t2是两个协程
步骤一 t1 首次访问 mi.com
	执行首次查询
步骤二 t1 查询终止
	done返回终止消息，删除map中对应的value，关闭通道，进行广播
步骤三 t2 此时访问访问 mi.com 读map

 步骤二和步骤三可能会同时对map的同一个Key进行读写，这里是不是没有进行并发处理

**Comment by linehk** [comment]
确实会在 `e := cache[req.key]` 出现并发的问题。

解决方案如下：
1. 使用时，保证入参的 URL 是唯一的；
2. 对 map 加锁；
3. 使用 sync.Map。

**Comment by linehk** [comment]
@shangxiaomi
