### ISSUE TITLE
import "C" regenerate cgo definitions

### ISSUE THREAD

**Issue by liangweidonggood** [linehk/gopl#12]
ch13\biz\bzip2.go里面的出现这个import "C" regenerate cgo definitions应该怎么处理

**Comment by linehk** [comment]
https://c0mm4nd.com/post/regenerate-cgo-definitions/
https://github.com/golang/go/issues/35721
https://www.reddit.com/r/vscode/comments/hjphbz/what_is_the_purpose_of_regenerate_cgo_definitions/

看起来像是使用 cgo 和 go tools 才会出现的问题，可以不用理会，详细信息请看上面的链接。

**Comment by linehk** [comment]
@liangweidonggood
