### ISSUE TITLE
exercise2.5/popcount.go 去掉&之后运行很慢

### ISSUE THREAD

**Issue by peter-wow** [linehk/gopl#18]
https://github.com/linehk/gopl/blob/8de92868226c0fc382a87f6de475a6342a181204/ch2/exercise2.5/popcount.go#L28

如果去掉 `&`  变成 `x = x - 1` 那么执行变得很慢  

是不是去掉之后每次循环都需要开辟一块内存空间导致程序慢的?

**Comment by linehk** [comment]
没看懂，为什么要去掉 `&`？本来就是要用来做与运算的。

**Comment by peter-wow** [comment]
> 没看懂，为什么要去掉 `&`？本来就是要用来做与运算的。

哦对是 与 我搞错了~
