### ISSUE TITLE
题目 判断两个字符串是否是相互打乱 那如何两个字符串完成相等也返回true 是否是一个BUG~

### ISSUE THREAD

**Issue by peter-wow** [linehk/gopl#19]
https://github.com/linehk/gopl/blob/8de92868226c0fc382a87f6de475a6342a181204/ch3/exercise3.12/main.go#L11

如果是可以PR一个~ 

```golang
if s1 == s2 {
   return false
}
```

**Comment by linehk** [comment]
完全相等应该也要返回 true。
搜了一下，别人也是这样理解的：
https://github.com/torbiak/gopl/blob/master/ex3.12/anagram.go
https://github.com/kdama/gopl/blob/master/ch03/ex12/main.go
