### ISSUE TITLE
exercise4.1 中的与比较问题

### ISSUE THREAD

**Issue by peter-wow** [linehk/gopl#20]
这儿为什么是要与后比较, 而不能是直接 `b1 != b2` 

https://github.com/linehk/gopl/blob/8de92868226c0fc382a87f6de475a6342a181204/ch4/exercise4.1/main.go#L26

**Comment by zhqinux** [comment]
原代码的意图是比较单个bit 位不同的个数
b1&mask 这是在清除其他bit位
比如 b1 = 01101100 b2 = 01100110
当mask = 00000001时
b1 & mask -> 00000000
b2 & mask -> 00000000
所以b1 和 b2 最后1个bit位是相同的
如果不进行 b1&mask != b2&mask 直接进行 b1 != b2
那么结果永远是true
