### ISSUE TITLE
ch7-ex7.1中为什么是len(p) 而不是c呢

### ISSUE THREAD

**Issue by jacky-pony** [linehk/gopl#21]
https://github.com/linehk/gopl/blob/8de92868226c0fc382a87f6de475a6342a181204/ch7/exercise7.1/main.go#L20-L30

**Comment by linehk** [comment]
题目是这样的，练习 7.1：**使用来自 ByteCounter 的思路**，实现一个针对单词和行数的计数器。你会发现 bufio.ScanWords 非常的有用。

书里面的 ByteCounter 如下：

```go
type ByteCounter int

func (c *ByteCounter) Write(p []byte) (int, error) {
	*c += ByteCounter(len(p)) // convert int to ByteCounter
	return len(p), nil
}
```

它也是返回的 len(p)。

c 的底层数据类型为 int，返回 len(c) 会发生错误：`./prog.go:29:12: invalid argument c (type *WordCounter) for len`。
